import { Inter } from 'next/font/google'
import Image from 'next/image'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
<html lang="en">
<body>
  <div className="content_block header">
    <Image id="logo_main" height={45} width={45} src="/assets/logo.svg" alt="Codeacademy"/>
    <button className="header_button">Catalog</button>
    <button className="header_button">Resources</button>
    <button className="header_button">Community</button>
    <button className="header_button">Pricing</button>
    <button className="header_button">Business Solutions</button>
    <button className="header_button sq final">
      <Image height={20} width={20} id="logo_search"  src="/assets/search.svg" alt="Search"/>
    </button>
    <button className="header_button sq">Log In</button>
  </div>  
  <div className="login_form section">
    <div className="form_body content_block">
      <div className="images">
        <Image height={500} width={500} src="/assets/slash.svg" alt="Intro"/>
        <Image height={500} width={500} src="/assets/img.jpg" alt="Intro"/>
      </div>
      <div className="form">
        <div className="form_header">Join the millions learning to code with Codecademy for free</div>  
        <label>Email</label>
        <input type="email"/>
        <label>Password</label>
        <input type="password"/>
        <button className="signup">Sign up</button>
        <p className="t_and_c">By signing up for Codecademy, you agree to Codecademy's <a href="">Terms of Service</a> & <a href="">Privacy Policy</a>.</p>
        <p className="alternatives">Or sign up using: </p>
        <div className="social_buttons">
          <div className="social_button"><Image height={25} width={25} src="/assets/linkedin.svg" alt="LinkedIn"/> </div>
          <div className="social_button"><Image height={25} width={25} src="/assets/google.svg" alt="Google"/> </div>
          <div className="social_button"><Image height={25} width={25} src="/assets/facebook.svg" alt="Facebook"/> </div>
          <div className="social_button"><Image height={25} width={25} src="/assets/github.svg" alt="Github"/></div>
        </div>
      </div>
    </div>
  </div>
  <div className="code_editor section">
    <div className="editor_body content_block">
      <Image height={430} width={660} src="/assets/editor.png" alt="Editor" />
      <div className="editor_right">
        <label>Beginners Welcome</label>
        <p className="editor_title">Start Coding in seconds</p>
        <p>Go ahead, give it a try. Our hands-on learning environment means you'll be writing real code from your very first lesson.</p>
        <div className="editor_buttons">
          <button className="left">Continue Lesson</button>
          <button className="right">More beginner courses</button>
        </div>
      </div>
    </div>
  </div>
  <div className="quiz section">
    <div className="content_block">
      <section>
        <header>Not sure where to start?</header>
        <p>This short quiz will sort you out. Answer a few simple questions to get personal career advice and course recommendations.</p>
        <button className="button">Take the quiz</button> 
      </section>
      <section>
        <Image height={300} width={180} src="/assets/window.svg" />
      </section>
    </div>
  </div>
  <div className="stories section">
    <Image src="/assets/grid.svg" height={100} width={0} className="background"/>
    <div className="stories_body content_block">
      <p>Stories from real people</p>
      <section>
        <p>Watch and read stories from the Codecademy community.</p>
        <button className="button">Explore more stories </button>
      </section>
      <section>
        <div className="learner">
          <Image height={270} width={270} src="/assets/learner_1.jpg" alt="Portriat"/>
          <h4>Taking a different path: One Team Lead's story</h4>
          <p>Giacomo S., Team Lead, London</p>
        </div>
        <div className="learner">
          <Image height={270} width={270} src="/assets/learner_2.jpg" alt="Portriat"/>
          <h4>Taking a different path: One Team Lead's story</h4>
          <p>Giacomo S., Team Lead, London</p>
        </div>
        <div className="learner">
          <Image height={270} width={270} src="/assets/learner_3.jpeg" alt="Portriat"/>
          <h4>Taking a different path: One Team Lead's story</h4>
          <p>Giacomo S., Team Lead, London</p>
        </div>
        <div className="learner">
          <Image height={270} width={270} src="/assets/learner_4.jpg" alt="Portriat"/>
          <h4>Taking a different path: One Team Lead's story</h4>
          <p>Giacomo S., Team Lead, London</p>
        </div>
      </section>
    </div>
  </div>
  <div className="stats_container section">
    <div className="content_block">
      <header>Join in on something big</header>
      <section className="stats">
        <div className="stat">
          <p>50M</p>
          <p>Learners</p>
        </div>
        <div className="stat">
          <p>190+</p>
          <p>Countries</p>
        </div>
        <div className="stat">
          <p>3.7B</p>
          <p>Code Submits</p>
        </div>
      </section>
    </div>
  </div>
  <div className="explore section">
    <div className="content_block">
      <section>
        <Image height={50} width={144} src="/assets/logox.svg" alt="LOGO"/>
        <header>Level up your team's skills</header>
        <p>Give your team the knowledge, experience, and confidence they need to tackle any problem.</p>
        <button className="button">Explore business plans</button>
      </section>
      <Image height={300} width={300} src="/assets/hive.svg" alt="hive"/>
    </div>  
  </div>
  <div className="start_free section">
    <div className="content_block">
      <section>
        <Image height={300} width={450} src="/assets/imgs.png"/>
      </section>
      <section>
        <header>Start for free</header>
        <p>If you’ve made it this far, you must be at least a little curious. Sign up and take the first step toward your goals.</p>
        <button className="button">Sign Up</button> 
      </section>
    </div>
  </div>
  <div className="footer section"></div>
</body>
</html>
  )
}
